# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wiki-Toolkit-Formatter-UseMod
version:      0.20
version_from: lib/Wiki/Toolkit/Formatter/UseMod.pm
installdirs:  site
requires:
    HTML::PullParser:              0
    Test::MockObject:              0.07
    Test::More:                    0
    Text::WikiFormat:              0.71
    URI::Escape:                   0
    URI::Find::Delimited:          0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
